

import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.SwingConstants;

/**
 *
 * @author admin
 */
public class Billing extends javax.swing.JFrame {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
PreparedStatement pst1 = null;
ResultSet rs1 = null;
String tableClicked = "";
    /**
     * Creates new form Billing
     */
    Billing() throws Exception {
        initComponents();
       String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date()); 
       billDate.setText(date);
		Class.forName("com.mysql.cj.jdbc.Driver");
	conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical_store","root","");
        try{
          String sql = "SELECT  mname as 'Medicine Name',mtype as 'Type',msaleprice as 'Price',mexpdate as 'Expiry date' FROM medicine";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            medicinetable.setModel(DbUtils.resultSetToTableModel(rs));
            
            String sql1 = "Select MAX(billno) FROM billing";
            pst1 = conn.prepareStatement(sql1);
            rs1 = pst1.executeQuery();
            while(rs1.next())
            {
            int billno=rs1.getInt(1);
            billno=billno+1;
            billNO.setText(String.valueOf(billno));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
//    	setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//setVisible(true);
//WindowListener exitListener = new WindowAdapter() {
//
//    @Override
//    public void windowClosing(WindowEvent e) {
//        try {
//			setVisible(false);
//		} catch (Exception e1) {
//			// TODO Auto-generated catch block
//			e1.printStackTrace();
//		}
//    }
//};
//this.addWindowListener(exitListener);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        billNO = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        billDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cusName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cusPhno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        billTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicinetable = new javax.swing.JTable();
        addToBill = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        printBTn = new javax.swing.JButton();
        removeMedicine = new javax.swing.JButton();
        clearTable = new javax.swing.JButton();
        totalButton = new javax.swing.JButton();
        saveBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medical Store Bill");

        jLabel2.setText("Bill No. :");

        billNO.setText("jLabel3");

        jLabel4.setText("Date :");

        billDate.setText("jLabel5");

        jLabel6.setText("Customer Name :");

        jLabel7.setText("Customer Ph.No:");

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Type", "Price", "Quantity", "Total"
            }
        ));
        productTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(productTable);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Net Amount :");

        billTotal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        billTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billTotal.setText("0");
        
        JLabel jLabel8_1 = new JLabel();
        jLabel8_1.setText("Total Bill :");
        jLabel8_1.setFont(new Font("Times New Roman", Font.PLAIN, 12));
        
        NetTotal = new JLabel();
        NetTotal.setText("0");
        NetTotal.setHorizontalAlignment(SwingConstants.CENTER);
        NetTotal.setFont(new Font("Times New Roman", Font.PLAIN, 12));
        
        jLabel8_2 = new JLabel();
        jLabel8_2.setText("Total GST 18%  :");
        jLabel8_2.setFont(new Font("Times New Roman", Font.PLAIN, 12));
        
        TotalwithGST = new JLabel();
        TotalwithGST.setText("0");
        TotalwithGST.setHorizontalAlignment(SwingConstants.CENTER);
        TotalwithGST.setFont(new Font("Times New Roman", Font.PLAIN, 12));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGap(161)
        						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addContainerGap()
        						.addComponent(jLabel2)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(billNO, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        						.addGap(136)
        						.addComponent(jLabel4)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(billDate, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addContainerGap()
        						.addComponent(jLabel6)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(cusName))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addContainerGap()
        						.addComponent(jLabel7)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(cusPhno)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel8_1, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        		.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel8_2, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8))
        			.addPreferredGap(ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(NetTotal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(billTotal, GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        				.addComponent(TotalwithGST, GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(billNO)
        				.addComponent(jLabel4)
        				.addComponent(billDate))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(cusName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(cusPhno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 296, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8_1)
        				.addComponent(billTotal, GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        			.addGap(3)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8_2)
        				.addComponent(TotalwithGST, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(NetTotal, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        medicinetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Medicine Name", "Type", "Price", "Expiry date"
            }
        ));
        jScrollPane2.setViewportView(medicinetable);

        addToBill.setText("Add to Bill");
        addToBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBillActionPerformed(evt);
            }
        });

        backButton.setText("Back to Main page");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(addToBill)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addToBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton))
        );

        printBTn.setText("Print");
        printBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBTnActionPerformed(evt);
            }
        });

        removeMedicine.setText("Remove");
        removeMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMedicineActionPerformed(evt);
            }
        });

        clearTable.setText("Clear");
        clearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTableActionPerformed(evt);
            }
        });

        totalButton.setText("Total");
        totalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalButtonActionPerformed(evt);
            }
        });

        saveBill.setText("Save Bill");
        saveBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalButton)
                            .addComponent(printBTn))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeMedicine)
                                .addGap(100, 100, 100)
                                .addComponent(clearTable))
                            .addComponent(saveBill))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalButton)
                            .addComponent(saveBill))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printBTn)
                            .addComponent(removeMedicine)
                            .addComponent(clearTable))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void removeMedicineActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
         TableModel model1=productTable.getModel();
                               int[] indexes = productTable.getSelectedRows();
                               Object[] row = new Object[4];
                               DefaultTableModel model2 = (DefaultTableModel) productTable.getModel();
                               for(int i=0;i<indexes.length;i++)
                               {
                                   
                                    model2.removeRow(i);
                               }
        
    }                                              

    private void addToBillActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
                        int qtyval;
                        int des = JOptionPane.showConfirmDialog(null, "Are you sure you want to Add this record?","Delete",JOptionPane.YES_NO_OPTION);
                        if (des==0){
                            try{
                               TableModel model1=medicinetable.getModel();
                               int[] indexes = medicinetable.getSelectedRows();
                               Object[] row = new Object[4];
                               DefaultTableModel model2 = (DefaultTableModel) productTable.getModel();
                               for(int i=0;i<indexes.length;i++)
                               {
                                   row[0]=model1.getValueAt(indexes[i], 0);
                                   row[1]=model1.getValueAt(indexes[i], 1);
                                   row[2]=model1.getValueAt(indexes[i], 2);
                                  
                                   qtyval=parseInt(JOptionPane.showInputDialog("Enter Quantity:"));
                                   row[3]=qtyval;
//                                   int v1;
//                                   v1 = Integer.parseInt(medicinetable.getValueAt(i, 2).toString());
//                                   
//                                    
//                                   int total=v1*qtyval;
//                                   row[4]=total;
                                    model2.addRow(row);
                               }
                                
                               
                             }catch(Exception e){
                                JOptionPane.showMessageDialog(null, e.getMessage());
                             }
               
                        }
    }                                         

    private void totalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
         double totalBill = 0.0;
        TableModel model1=productTable.getModel();
        int index=model1.getRowCount();
        for(int i=0;i<index;i++)
        {
            Float v1=Float.parseFloat(productTable.getValueAt(i, 2).toString()) ;
            Float v2=Float.parseFloat(productTable.getValueAt(i, 3).toString()) ;
            
            Float total=v1*v2;
            model1.setValueAt(total, i, 4);
        }
          for(int j=0;j<index;j++)
          {
              
              Float Amount =Float.parseFloat(productTable.getValueAt(j, 4).toString());
              totalBill = Amount+totalBill;
              
              
          }
            billTotal.setText(String.valueOf(totalBill));
            double gst=(totalBill*18)/100;
            TotalwithGST.setText(String.valueOf(gst));
            
            double netval=totalBill+gst;
            NetTotal.setText(String.valueOf(netval));
    }                                           

    private void clearTableActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) productTable.getModel();
        int index=model2.getRowCount();
        model2.setRowCount(0);
        billTotal.setText("0");
    }                                          

    private void printBTnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Toolkit tkp = jPanel1.getToolkit();
        PrintJob pjp = tkp.getPrintJob(this, null, null);
        Graphics g = pjp.getGraphics();
        jPanel1.print(g);
        g.dispose();
        pjp.end();
         
        
    }                                        

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	setVisible(false);
    }                                          

    private void saveBillActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         
        
//            String custName=cusName.getText();
//            String custNo=cusPhno.getText();
             if(cusName.getText().equals("") && cusPhno.getText().equals(""))
             {
                 JOptionPane.showMessageDialog(null, "Please Enter Customer Name and Ph.No.");
//                 try {
//                     jButton1ActionPerformed(evt);
//                 } catch (Exception ex) {
//                     Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
//                 }
             }
             else
             {
                 try {
                     addbill();
                 } catch (Exception ex) {
                     Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
               
    }                                        

    void addbill() throws Exception
    {
		Class.forName("com.mysql.cj.jdbc.Driver");
	conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical_store","root","");
        String sql  = "INSERT INTO billing(billno,bdate,cusName,cusPhno,totalbill) VALUES (?,?,?,?,?)";
   
        pst = conn.prepareStatement(sql);
    
                
                pst.setInt(1, Integer.parseInt(billNO.getText()));
                pst.setString(2, billDate.getText());
                pst.setString(3, cusName.getText());
                pst.setString(4, cusPhno.getText());
                pst.setInt(5, (int) Float.parseFloat(NetTotal.getText()));
                pst.execute();
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        new Billing();
    } catch (Exception ex) {
        Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
    }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Billing().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addToBill;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel billDate;
    private javax.swing.JLabel billNO;
    private javax.swing.JLabel billTotal;
    private javax.swing.JButton clearTable;
    private javax.swing.JTextField cusName;
    private javax.swing.JTextField cusPhno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable medicinetable;
    private javax.swing.JButton printBTn;
    private javax.swing.JTable productTable;
    private javax.swing.JButton removeMedicine;
    private javax.swing.JButton saveBill;
    private javax.swing.JButton totalButton;
    private JLabel NetTotal;
    private JLabel jLabel8_2;
    private JLabel TotalwithGST;
    // End of variables declaration                   

    private boolean isempty(JTextField cusName) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
